### ISSUE TITLE
???

### ISSUE THREAD

**Issue by pierrelasse** [ItsALisName/Protocoller#1]
Hello!
I don't know why this plugin does not have any comments or many downloads but it looks like it could be as good as ProtocolLib when looking at the API but what is kinda ඞsusඞ is that it is that good but has no downloads? If it is really your plugin that you made thats crazy.

Also do you have any support discord?

**Comment by ItsALisName** [comment]
Hello, thank you very much for a good review, nice! Regarding the fact that few people use it, it seems to me that everyone is just used to ProtocolLib and does not want to switch to something new, and in addition this plugin has been released quite recently, I think everything is still ahead =D

No, there is no Discord channel yet, I think I will add it soon!
